# https://taskfile.dev

version: '3'

vars:
  BINARY_FOLDER: bin
  NAME: influxdb-v2
  GOLANGCI_LINT_VERSION: v1.52.2
  VERSION: v0.4.5
  NAMESPACE: hasanhakkaev

dotenv: ['.env']

tasks:
  init:
    desc: Initialize for development
    cmds:
      - go install
      - go mod tidy
      - go mod vendor
  build:
    desc: Build the provider binary
    cmds:
      - go build -v -o {{.BINARY_FOLDER}}/terraform-provider-{{.NAME}}_{{.VERSION}}
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
    generates:
      - ' go build -v -o {{.BINARY_FOLDER}}/terraform-provider-{{.NAME}}_{{.VERSION}}'
  test:
    desc: Run unit tests
    cmds:
      - go test -tags=unit -v -cover ./...
  docs:
    desc: Update the generated documentation
    cmds:
      - go generate
    sources:
      - "main.go"
      - "influxdbv2/**/*.go"
      - "examples/**/*.tf"
      - go.mod
      - go.sum
    generates:
      - docs/**/*.md
  lint:
    desc: Run linters
    deps:
      - install-golangci-lint
    cmds:
      - golangci-lint run ./influxdbv2/...
    sources:
      - "influxdbv2\\**\\*.go"
      - go.mod
      - go.sum
      - .golangci.yml

  install-golangci-lint:
    desc: Install the golangci-lint tool
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}}
    status:
      - which golangci-lint
      - golangci-lint version | grep {{.GOLANGCI_LINT_VERSION}}
  start-influx:
    desc: Start InfluxDB
    cmds:
      - ./scripts/setup_influxdb.sh
  stop-influx:
    desc: Stop InfluxDB
    cmds:
        - docker stop tf_acc_tests_influxdb
        - docker rm tf_acc_tests_influxdb